export const chatConstants = {
    MESSAGE_SEND_REQUEST: 'MESSAGE_SEND_REQUEST',
    MESSAGE_SEND_SUCCESS: 'MESSAGE_SEND_SUCCESS',
    MESSAGE_SEND_FAILURE: 'MESSAGE_SEND_FAILURE',
    MESSAGE_GET_REQUEST: 'MESSAGE_GET_REQUEST',
    MESSAGE_GET_SUCCESS: 'MESSAGE_GET_SUCCESS',
    MESSAGE_GET_FAILURE: 'MESSAGE_GET_FAILURE',
}