export const forumConstants = {
    POST_SEND_REQUEST: 'POST_SEND_REQUEST',
    POST_SEND_SUCCESS: 'POST_SEND_SUCCESS',
    POST_SEND_FAILURE: 'POST_SEND_FAILURE',
    POST_GET_REQUEST: 'POST_GET_REQUEST',
    POST_GET_SUCCESS: 'POST_GET_SUCCESS',
    POST_GET_FAILURE: 'POST_GET_FAILURE',
    POST_ANSWER_ADD_REQUEST: 'POST_ANSWER_ADD_REQUEST',
    POST_ANSWER_ADD_SUCCESS: 'POST_ANSWER_ADD_SUCCESS',
    POST_ANSWER_ADD_FAILURE: 'POST_ANSWER_ADD_FAILURE',
}